# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeokodowanieAdresow
                                 A QGIS plugin
 Wtyczka geokoduje adresy z pliku do warstwy punktowej
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-13
        copyright            : (C) 2024 by EnviroSolutions Sp. z o.o.
        email                : office@envirosolutions.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

import os
import configparser


"""Wersja wtyczki"""
plugin_name = ''
plugin_version = ''

config = configparser.ConfigParser()
try:
    with open(os.path.join(os.path.dirname(__file__), 'metadata.txt'), 'r', encoding='utf-8') as f:
        config.read_file(f)
    plugin_name = config.get('general', 'name')
    plugin_version = config.get('general', 'version')
except Exception:
    pass

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeokodowanieAdresow class from file GeokodowanieAdresow.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #    
    from .geokodowanie_adresow import GeokodowanieAdresow
    return GeokodowanieAdresow(iface)
