# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geokodowanie_adresow_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GeokodowanieAdresowDialogBase(object):
    def setupUi(self, GeokodowanieAdresowDialogBase):
        GeokodowanieAdresowDialogBase.setObjectName("GeokodowanieAdresowDialogBase")
        GeokodowanieAdresowDialogBase.resize(531, 504)
        self.button_box = QtWidgets.QDialogButtonBox(GeokodowanieAdresowDialogBase)
        self.button_box.setGeometry(QtCore.QRect(390, 410, 111, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.button_box.setObjectName("button_box")
        self.label = QtWidgets.QLabel(GeokodowanieAdresowDialogBase)
        self.label.setGeometry(QtCore.QRect(20, 30, 251, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnInputFile = QtWidgets.QPushButton(GeokodowanieAdresowDialogBase)
        self.btnInputFile.setGeometry(QtCore.QRect(410, 20, 93, 28))
        self.btnInputFile.setObjectName("btnInputFile")
        self.lblInputFile = QtWidgets.QLabel(GeokodowanieAdresowDialogBase)
        self.lblInputFile.setGeometry(QtCore.QRect(20, 50, 531, 20))
        self.lblInputFile.setObjectName("lblInputFile")
        self.label_2 = QtWidgets.QLabel(GeokodowanieAdresowDialogBase)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 381, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnOutputFile = QtWidgets.QPushButton(GeokodowanieAdresowDialogBase)
        self.btnOutputFile.setGeometry(QtCore.QRect(410, 90, 93, 28))
        self.btnOutputFile.setObjectName("btnOutputFile")
        self.lblOutputFile = QtWidgets.QLabel(GeokodowanieAdresowDialogBase)
        self.lblOutputFile.setGeometry(QtCore.QRect(20, 120, 531, 21))
        self.lblOutputFile.setObjectName("lblOutputFile")
        self.btnGeokoduj = QtWidgets.QPushButton(GeokodowanieAdresowDialogBase)
        self.btnGeokoduj.setEnabled(False)
        self.btnGeokoduj.setGeometry(QtCore.QRect(410, 350, 93, 28))
        self.btnGeokoduj.setObjectName("btnGeokoduj")
        self.layoutWidget = QtWidgets.QWidget(GeokodowanieAdresowDialogBase)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 300, 231, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbxMiejscowosc = QtWidgets.QComboBox(self.layoutWidget)
        self.cbxMiejscowosc.setObjectName("cbxMiejscowosc")
        self.verticalLayout.addWidget(self.cbxMiejscowosc)
        self.cbxUlica = QtWidgets.QComboBox(self.layoutWidget)
        self.cbxUlica.setObjectName("cbxUlica")
        self.verticalLayout.addWidget(self.cbxUlica)
        self.cbxNumer = QtWidgets.QComboBox(self.layoutWidget)
        self.cbxNumer.setObjectName("cbxNumer")
        self.verticalLayout.addWidget(self.cbxNumer)
        self.cbxKod = QtWidgets.QComboBox(self.layoutWidget)
        self.cbxKod.setObjectName("cbxKod")
        self.verticalLayout.addWidget(self.cbxKod)
        self.layoutWidget1 = QtWidgets.QWidget(GeokodowanieAdresowDialogBase)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 300, 121, 141))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.lbl_pluginVersion = QtWidgets.QLabel(GeokodowanieAdresowDialogBase)
        self.lbl_pluginVersion.setGeometry(QtCore.QRect(20, 470, 241, 20))
        self.lbl_pluginVersion.setObjectName("lbl_pluginVersion")
        self.lbl_copyrights = QtWidgets.QLabel(GeokodowanieAdresowDialogBase)
        self.lbl_copyrights.setGeometry(QtCore.QRect(310, 470, 201, 20))
        self.lbl_copyrights.setTextFormat(QtCore.Qt.RichText)
        self.lbl_copyrights.setOpenExternalLinks(True)
        self.lbl_copyrights.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.lbl_copyrights.setObjectName("lbl_copyrights")
        self.img_main = QtWidgets.QLabel(GeokodowanieAdresowDialogBase)
        self.img_main.setGeometry(QtCore.QRect(400, 150, 121, 111))
        self.img_main.setText("")
        self.img_main.setPixmap(QtGui.QPixmap("images/icon_uug.svg"))
        self.img_main.setScaledContents(True)
        self.img_main.setObjectName("img_main")
        self.cbxFirstRow = QtWidgets.QCheckBox(GeokodowanieAdresowDialogBase)
        self.cbxFirstRow.setGeometry(QtCore.QRect(20, 260, 331, 20))
        self.cbxFirstRow.setChecked(True)
        self.cbxFirstRow.setObjectName("cbxFirstRow")
        self.lblEncoding = QtWidgets.QLabel(GeokodowanieAdresowDialogBase)
        self.lblEncoding.setGeometry(QtCore.QRect(18, 170, 121, 21))
        self.lblEncoding.setObjectName("lblEncoding")
        self.cbxEncoding = QtWidgets.QComboBox(GeokodowanieAdresowDialogBase)
        self.cbxEncoding.setGeometry(QtCore.QRect(158, 170, 111, 22))
        self.cbxEncoding.setObjectName("cbxEncoding")
        self.label_7 = QtWidgets.QLabel(GeokodowanieAdresowDialogBase)
        self.label_7.setGeometry(QtCore.QRect(18, 210, 181, 21))
        self.label_7.setObjectName("label_7")
        self.led_symbol = QtWidgets.QLineEdit(GeokodowanieAdresowDialogBase)
        self.led_symbol.setGeometry(QtCore.QRect(240, 210, 31, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.led_symbol.setFont(font)
        self.led_symbol.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.led_symbol.setObjectName("led_symbol")

        self.retranslateUi(GeokodowanieAdresowDialogBase)
        self.button_box.accepted.connect(GeokodowanieAdresowDialogBase.accept)
        self.button_box.rejected.connect(GeokodowanieAdresowDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(GeokodowanieAdresowDialogBase)

    def retranslateUi(self, GeokodowanieAdresowDialogBase):
        _translate = QtCore.QCoreApplication.translate
        GeokodowanieAdresowDialogBase.setWindowTitle(_translate("GeokodowanieAdresowDialogBase", "Geokodowanie Adresów"))
        self.label.setText(_translate("GeokodowanieAdresowDialogBase", "Wybierz plik z adresami (CSV)"))
        self.btnInputFile.setText(_translate("GeokodowanieAdresowDialogBase", "..."))
        self.lblInputFile.setText(_translate("GeokodowanieAdresowDialogBase", "..."))
        self.label_2.setText(_translate("GeokodowanieAdresowDialogBase", "Wskaż plik do zapisu niezgeokodowanych adresów"))
        self.btnOutputFile.setText(_translate("GeokodowanieAdresowDialogBase", "..."))
        self.lblOutputFile.setText(_translate("GeokodowanieAdresowDialogBase", "..."))
        self.btnGeokoduj.setText(_translate("GeokodowanieAdresowDialogBase", "Geokoduj"))
        self.label_3.setText(_translate("GeokodowanieAdresowDialogBase", "Miejscowość"))
        self.label_4.setText(_translate("GeokodowanieAdresowDialogBase", "Ulica"))
        self.label_5.setText(_translate("GeokodowanieAdresowDialogBase", "Numer Porządkowy"))
        self.label_6.setText(_translate("GeokodowanieAdresowDialogBase", "Kod Pocztowy"))
        self.lbl_pluginVersion.setText(_translate("GeokodowanieAdresowDialogBase", "Geokodowanie adresów UUG GUGiK 1.0"))
        self.lbl_copyrights.setText(_translate("GeokodowanieAdresowDialogBase", "© 2024 <a href=\"http://www.envirosolutions.pl/\">EnviroSolutions Sp. z o.o.</a>"))
        self.cbxFirstRow.setText(_translate("GeokodowanieAdresowDialogBase", "Pierwszy wiersz zawiera nazwy kolumn"))
        self.lblEncoding.setText(_translate("GeokodowanieAdresowDialogBase", "Kodowanie znaków:"))
        self.label_7.setText(_translate("GeokodowanieAdresowDialogBase", "Znak rozdzielający kolumny"))
        self.led_symbol.setText(_translate("GeokodowanieAdresowDialogBase", ","))

